import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">HomeOne</Link>
        </li>
        <li>
          <Link to="/hometwo">HomeTwo</Link>
        </li>
        <li>
          <Link to="/register">Register</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/loginadmin">LoginAdmin</Link>
        </li>
        <li>
          <Link to="/logindoc">LoginDoc</Link>
        </li>
        <li>
          <Link to="/loginrec">LoginRec</Link>
        </li>
        <li>
          <Link to="/loginlab">LoginLab</Link>
        </li>
        <li>
          <Link to="/admin">Admin</Link>
        </li>
        <li>
          <Link to="/docdetail">DocDetail</Link>
        </li>
        <li>
          <Link to="/laboratorian">Laboratorian</Link>
        </li>
        <li>
          <Link to="/receptionist">Receptionist</Link>
        </li>
        <li>
          <Link to="/precription">Precription</Link>
        </li>
        <li>
          <Link to="/patient">Patient</Link>
        </li>
        <li>
          <Link to="/labtest">LabTest</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
